const DOCUMENT_NOT_FOUND_ERROR_CODE = 404;
const BAD_REQUEST_ERROR_CODE = 400;
const SERVER_ERROR_CODE = 500;
const UNAUTHORIZED_ERROR_CODE = 401;

module.exports = {
  DOCUMENT_NOT_FOUND_ERROR_CODE,
  BAD_REQUEST_ERROR_CODE,
  SERVER_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
};
